### ISSUE TITLE
AttributeError: 'NoneType' when models.json exist but none is installed

### ISSUE THREAD

**Issue by wasertech** [coqui-ai/stt-model-manager#44]
```
❯ stt-model-manager --debug
Installed models: ModelIndex(models=[ModelCard(name='French STT v0.9', language='French', version='v0.9', creator='commonvoice-fr', acoustic='https://coqui.gateway.scarf.sh/french/commonvoice-fr/v0.9/model.tflite', scorer='https://coqui.gateway.scarf.sh/french/commonvoice-fr/v0.9/kenlm.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='Welsh STT v21.03', language='Welsh', version='v21.03', creator='Dewi Bryn Jones', acoustic='https://coqui.gateway.scarf.sh/welsh/techiaith/v21.03/model.tflite', scorer='https://coqui.gateway.scarf.sh/welsh/techiaith/v21.03/techiaith_bangor_transcribe_21.03.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='Catalan STT v0.14.0', language='Catalan', version='v0.14.0', creator="Ciaran O'Reilly", acoustic='https://coqui.gateway.scarf.sh/catalan/ccoreilly/v0.14.0/model.tflite', scorer='https://coqui.gateway.scarf.sh/catalan/ccoreilly/v0.14.0/kenlm-aina-3-p10.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='Ukrainian STT v0.4', language='Ukrainian', version='v0.4', creator='Yurii Paniv', acoustic='https://coqui.gateway.scarf.sh/ukrainian/robinhad/v0.4/model.tflite', scorer='https://coqui.gateway.scarf.sh/ukrainian/robinhad/v0.4/kenlm.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='German STT v0.9.0', language='German', version='v0.9.0', creator='Aashish Agarwal', acoustic='https://coqui.gateway.scarf.sh/german/AASHISHAG/v0.9.0/model.tflite', scorer='https://coqui.gateway.scarf.sh/german/AASHISHAG/v0.9.0/de-aashishag-1-prune-kenlm.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='Italian STT 2020.8.7', language='Italian', version='2020.8.7', creator='Mozilla Italia', acoustic='https://coqui.gateway.scarf.sh/italian/mozillaitalia/2020.8.7/model.tflite', scorer='https://coqui.gateway.scarf.sh/italian/mozillaitalia/2020.8.7/it-mzit-1-prune-kenlm.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='Greek STT v0.1.0', language='Greek', version='v0.1.0', creator='ITML', acoustic='https://coqui.gateway.scarf.sh/greek/itml/v0.1.0/model.tflite', scorer='https://coqui.gateway.scarf.sh/greek/itml/v0.1.0/Greek-digits-yesno.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='Irish STT v0.1.1', language='Irish', version='v0.1.1', creator='ITML', acoustic='https://coqui.gateway.scarf.sh/irish/itml/v0.1.1/model.tflite', scorer='https://coqui.gateway.scarf.sh/irish/itml/v0.1.1/Irish-digits-yesno.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='Breton STT v0.1.0', language='Breton', version='v0.1.0', creator='ITML', acoustic='https://coqui.gateway.scarf.sh/breton/itml/v0.1.0/model.tflite', scorer='https://coqui.gateway.scarf.sh/breton/itml/v0.1.0/Breton-digits-yesno.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='Polish STT v0.0.1', language='Polish', version='v0.0.1', creator='Jaco-Assistant', acoustic='https://coqui.gateway.scarf.sh/polish/jaco-assistant/v0.0.1/model.tflite', scorer='https://coqui.gateway.scarf.sh/polish/jaco-assistant/v0.0.1/kenlm_pl.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='English STT v1.0.0-huge-vocab', language='English', version='v1.0.0-huge-vocab', creator='Coqui', acoustic='https://coqui.gateway.scarf.sh/english/coqui/v1.0.0-huge-vocab/model.tflite', scorer='https://coqui.gateway.scarf.sh/english/coqui/v1.0.0-huge-vocab/huge-vocabulary.scorer', installed=False, acoustic_path=None, scorer_path=None), ModelCard(name='Russian STT v0.1.0', language='Russian', version='v0.1.0', creator='Joe Meyer', acoustic='https://coqui.gateway.scarf.sh/russian/jemeyer/v0.1.0/model.tflite', scorer='https://coqui.gateway.scarf.sh/russian/jemeyer/v0.1.0/wiki-ru-6gram.scorer', installed=False, acoustic_path=None, scorer_path=None)])
Traceback (most recent call last):
  File "/home/waser/.local/bin/stt-model-manager", line 8, in <module>
    sys.exit(main())
  File "/home/waser/.local/lib/python3.10/site-packages/coqui_stt_model_manager/__main__.py", line 13, in main
    app = build_app()
  File "/home/waser/.local/lib/python3.10/site-packages/coqui_stt_model_manager/server.py", line 278, in build_app
    app.config["MODEL_MANAGER"].maybe_upgrade_protobuf()
  File "/home/waser/.local/lib/python3.10/site-packages/coqui_stt_model_manager/modelmanager.py", line 280, in maybe_upgrade_protobuf
    pbmm_models = [
  File "/home/waser/.local/lib/python3.10/site-packages/coqui_stt_model_manager/modelmanager.py", line 281, in <listcomp>
    m for m in self.list_models() if m.acoustic_path.endswith(".pbmm")
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by wasertech** [comment]
With #45 
```zsh
❯ stt-model-manager
INFO:engineio.server:Server initialized for threading.
DEBUG:root:No installed models.
 * Serving Flask app 'coqui_stt_model_manager.server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:38450
Current installs: []
DEBUG:urllib3.connectionpool:http://127.0.0.1:38450 "GET / HTTP/1.1" 200 2945
Started server listening on http://127.0.0.1:38450 ...
Ouverture dans une session de navigateur existante.
Current installs: []
```
